### ISSUE TITLE
I am unable to compile Firefox through this PKGBUILD

### ISSUE THREAD

**Issue by ajakk** [afontenot/firefox-clean#2]
As the title says, Firefox doesn't compile when I run `makepkg` in the directory into which I pulled this repo. Given that the compile errors were undefined references, I thought that dependencies might be the issue. I reinstalled them all, to no avail.

[Abridged output of makepkg, with part of the make directory redacted.](https://pastebin.com/qhxsjG76)

**Comment by Cj-Malone** [comment]
Can you compile the the normal Firefox?

https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/firefox

**Comment by ajakk** [comment]
It compiled from that repo, no problems.

**Comment by ajakk** [comment]
I cloned the repo again and firefox-clean compiled.
